### ISSUE TITLE
Include sample docker-compose

### ISSUE THREAD

**Issue by Fmstrat** [danielguerra69/security-onion#1]
It would be very handy to have a sample docker-compose to determine which folders, like `/var/lib/mysql` or `/nsm` should be volumes, and what ports to open/forward.

**Comment by danielguerra69** [comment]
This just an ubuntu with security onion repository. Nothing is installed so there are no volumes for mysql etc. What do you want ?

**Comment by Fmstrat** [comment]
I'm new to SO, but I was planning to try to use this as a base for setting up a N/HIDS system on a local network (potentially running in host mode). What I'm seeing from the SO setup is that this is where files change:

Volumes:
- /var/lib/mysql
- /nsm
- /opt

Files that change:
- /etc/network/interfaces
- /etc/host

Ports:
- 22
- 443

I'm thinking I may need to build a separate Dockerfile that pulls this off, though.

**Comment by danielguerra69** [comment]
It basicly uses the same as ubuntu. First read howto make Dockerfile's and the about docker-compose to create what you need. So what you ask it not in my scope.
You could use the image like this
docker run -v /home/fmstrat/interfaces:/etc/network/interfaces -v /home/fmstrat/mynsm:/nsm for your volumes
